// Generated by CoffeeScript 1.6.3
(function() {
  var actionUtil;

  actionUtil = require('./helpers/actionUtil');

  module.exports = function(req, res) {
    var Model, childPk, parentPk, relation, where, _base, _base1;
    Model = actionUtil.parseModel(req);
    relation = req.options.alias;
    if (!relation || !Model) {
      return res.serverError();
    }
    if ((_base = req.options).criteria == null) {
      _base.criteria = {};
    }
    if ((_base1 = req.options.criteria).blacklist == null) {
      _base1.blacklist = ['limit', 'skip', 'sort', 'id', 'parentid'];
    }
    parentPk = req.param('parentid');
    childPk = actionUtil.parsePk(req);
    where = childPk ? [childPk] : actionUtil.parseCriteria(req);
    return Model.findOne(parentPk).populate(relation, {
      where: where,
      skip: actionUtil.parseSkip(req),
      limit: actionUtil.parseLimit(req),
      sort: actionUtil.parseSort(req)
    }).exec(function(err, parentRecord) {
      if (err) {
        return res.serverError(err);
      }
      if (!parentRecord) {
        return res.notFound("No record found with the specified `id`: " + parentPk);
      }
      if (!parentRecord[relation]) {
        return res.notFound("Specified record " + parentPk + " is missing relation " + relation + ".");
      }
      if (req._sails.hooks.pubsub && req.isSocket) {
        actionUtil.subscribeDeep(req, parentRecord);
      }
      return res.ok(parentRecord[relation]);
    });
  };

}).call(this);
